language: python
python:
  - "3.5"
  - "nightly"
sudo: required
install:
  - pytest
script:
  - pip install -r requirements.txt
  - python setup.py install
  - pytest tests/test_crypto.py
  - python crypto/crypto.py -v
