language: python
python:
  - "3.5"
  - "nightly"
sudo: required
install:
  - pytest
script:
  - pip install pytest
  - pip install -r requirements.txt
  - python setup.py
  - pytest
  - python __crypto__.py
